list:
  path:     /
  controller: App\Action\Admin\User\ListAction

edit:
  path:     /edit/{user}
  controller: App\Action\Admin\User\EditAction
  defaults: {user: null}

delete:
  path:     /{user}
  controller: App\Action\Admin\User\DeleteAction
